out_dir: results
metric_best: mae
metric_agg: argmin
dataset:
  dir: /data/beng/datasets
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  # edge_encoder_name: TypeDictEdge
  # edge_encoder_num_types: 4
  # edge_encoder_bn: False
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 7
  layers_post_mp: 1
  dim_inner: 130
  layer_type: my_gcnconv # generalconv
  stage_type: delay_gnn
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
nu: -1
nu_v2: True